### ISSUE TITLE
App hangs at startup if the last instance used becomes dormant

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-android#150]
Steps to reproduce:
 - Sign in as a user with access to a private instance
 - Force the instance to become dormant
 - The app will hang forever at the loading screen, and the only way to fix it is to reinstall the app

This is essentially a different variant of #22 and #125 

Error log output:
```
07-18 17:08:58.259    9603-9603/org.azavea.otm2.dev E/AZ_OTM﹕ Unable to Load Instance: null
    java.net.ConnectException
            at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:107)
            at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:54)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: org.apache.http.client.ClientProtocolException
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:557)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
            at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:73)
            at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:92)
            at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:54)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: org.apache.http.client.CircularRedirectException: Circular redirect to 'https://kolkata.internal.azavea.com/mike/dormant'
            at org.apache.http.impl.client.DefaultRedirectHandler.getLocationURI(DefaultRedirectHandler.java:173)
            at org.apache.http.impl.client.DefaultRequestDirector.handleResponse(DefaultRequestDirector.java:923)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:475)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
            at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:73)
            at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:92)
            at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:54)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

**Comment by maurizi** [comment]
I was not able to reproduce this.  I followed the steps but was kicked out to the instance switcher screen (which is what we want)
