### ISSUE TITLE
App crashes on Android 5.0 (Lollipop) on Main Map Screen in emulator

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-android#199]
The splash screen and the "Choose your instance" screen load fine, but when trying to open an instance (I used PhillyTreeMap), I get the following error in the adb logs and then the app crashes:

It then crashes every time you reload it, because it goes straight to the main map screen.

This is using the x86 image available through the SDK manager.

```
10-30 18:59:28.156    1966-1966/org.azavea.otm2.prod E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.azavea.otm2.prod, PID: 1966
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.azavea.otm2.prod/org.azavea.otm.ui.TabLayout}: java.lang.IllegalArgumentException: provider doesn't exist: network
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalArgumentException: provider doesn't exist: network
            at android.os.Parcel.readException(Parcel.java:1544)
            at android.os.Parcel.readException(Parcel.java:1493)
            at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:584)
            at android.location.LocationManager.requestLocationUpdates(LocationManager.java:867)
            at android.location.LocationManager.requestLocationUpdates(LocationManager.java:459)
            at org.azavea.otm.ui.MainMapActivity.setupLocationUpdating(MainMapActivity.java:717)
            at org.azavea.otm.ui.MainMapActivity.onCreateView(MainMapActivity.java:202)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:938)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:570)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
            at android.app.Activity.performStart(Activity.java:5949)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by maurizi** [comment]
I haven't seen this in any of my recent testing
