### ISSUE TITLE
Crash on main map page

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-android#221]
Reported via Google Play:
```
java.lang.NullPointerException
at org.azavea.otm.ui.MainMapActivity.showPopup(MainMapActivity.java:471)
at org.azavea.otm.ui.MainMapActivity.access$500(MainMapActivity.java:70)
at org.azavea.otm.ui.MainMapActivity$2.dataReceived(MainMapActivity.java:148)
at org.azavea.otm.ui.MainMapActivity$2.dataReceived(MainMapActivity.java:134)
at org.azavea.otm.rest.handlers.ContainerRestHandler.onSuccess(ContainerRestHandler.java:17)
at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:127)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5086)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by maurizi** [comment]
After some investigation I don't think it will be possible for this _particular_ error to appear again in the latest version of the app, because recent refactors have heavily changed this code path.
