### ISSUE TITLE
navigate up while adding tree crashes app

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-android#299]
The sequence I followed was this:

1. login to the app
2. add a tree
3. place a marker
4. tap the map while the add-tree step 2 form is showing to get back to the marker
5. tap the navigate-up OTM logo

I'd expect step 5 to just cancel the add operation, but it crashes the app.

I haven't tried it yet, but I'm guessing that the navigate-up any time after starting to add a tree will crash exactly the same way.

Here's the stacktrace:
```
                  Process: org.azavea.otm2.dev, PID: 23581
                  java.lang.IllegalArgumentException: Activity TreeMove does not have a parent activity name specified. (Did you forget to add the android.support.PARENT_ACTIVITY <meta-data>  element in your manifest?)
                      at android.support.v4.app.NavUtils.navigateUpFromSameTask(NavUtils.java:179)
                      at org.azavea.otm.ui.UpEnabledActionBarActivity.onOptionsItemSelected(UpEnabledActionBarActivity.java:19)
                      at android.app.Activity.onMenuItemSelected(Activity.java:3204)
                      at com.android.internal.widget.ActionBarView$2.onClick(ActionBarView.java:169)
                      at android.view.View.performClick(View.java:5697)
                      at android.view.View$PerformClick.run(View.java:22526)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7224)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by maurizi** [comment]
Using the up-navigation from other parts of the add tree process will just take the user back to the main map screen - only the "move tree" mode has this issue.
